spring:
  config:
    import: env.properties
    jwt:
      secret: ${JWT_SECRET}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_DATABASE_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
        data-locations: classpath:data/init.sql